[package]
name = "pycontrol"
version = "0.1.0"
authors = ["pyro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
bytes = "1.0.1"